const TYPES: { [key: string]: string } = {
  FETCH_TYPE_REQUESTS_SUCCESS: "FETCH_TYPE_REQUESTS_SUCCESS",
  FETCH_TYPE_REQUESTS_LOADING: "FETCH_TYPE_REQUESTS_LOADING",
  FETCH_TYPE_REQUESTS_ERROR: "FETCH_TYPE_REQUESTS_ERROR",
  CREATE_REQUEST_SUCCESS: "CREATE_REQUEST_SUCCESS",
  CREATE_REQUEST_LOADING: "CREATE_REQUEST_LOADING",
  CREATE_REQUEST_ERROR: "CREATE_REQUEST_ERROR",
  FETCH_MY_REQUEST_DATA_SUCCESS: "FETCH_MY_REQUEST_DATA_SUCCESS",
  FETCH_MY_REQUEST_DATA_LOADING: "FETCH_MY_REQUEST_DATA_LOADING",
  FETCH_MY_REQUEST_DATA_ERROR: "FETCH_MY_REQUEST_DATA_ERROR"
};

export { TYPES };
