steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "ci:${_ENV}"]
    env:
      - "REACT_APP_COMPANY=${_REACT_APP_COMPANY}"
  - name: "gcr.io/cloud-builders/docker"
    id: "docker build"
    args:
      [
        "build",
        "-f",
        "Dockerfile",
        "--tag=gcr.io/${PROJECT_ID}/${REPO_NAME}:latest",
        "--tag=gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker push(latest)"
    args: ["push", "gcr.io/${PROJECT_ID}/${REPO_NAME}:latest"]
  - name: "gcr.io/cloud-builders/docker"
    id: "docker push(COMMIT_SHA)"
    args: ["push", "gcr.io/${PROJECT_ID}/${REPO_NAME}:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - -c
      - |
        # <docker_image>@<digest>を取得
        export _image=$(docker inspect --format='{{index .RepoDigests 0}}' 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${COMMIT_SHA}')
        sed -i -e "s#REPLACED_WITH_DOCKER_IMAGE_NAME#${_image}#g" ./kubernetes/${_KUBERNETES_FILE}.yaml
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      "apply",
      "-f",
      "./kubernetes/${_KUBERNETES_FILE}.yaml"
    ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=wincalx"