apiVersion: apps/v1
kind: Deployment
metadata:
  name: wincalx-web
spec:
  selector:
    matchLabels:
      app: wincalx-web
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: wincalx-web
        tier: frontend
    spec:
      containers:
        - name: wincalx-web
          image: REPLACED_WITH_DOCKER_IMAGE_NAME
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: wincalx-web
spec:
  type: NodePort
  selector:
    app: wincalx-web
    tier: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 80